.github/workflows/unittests_python.yml
=> Update unit tests workflow.

README.md, ai_edge_torch/generative/README.md, ai_edge_torch/generative/examples/README.md, ai_edge_torch/generative/layers/README.md
=> Update READMEs badges and links

.github/workflows/nightly_pip_test.yml, README.md, setup.py
=> Added instructions for how to install the nightly package.

ai_edge_torch/generative/examples/t5/t5_conversion_colab.ipynb, docs/pytorch_converter/getting_started.ipynb, test/image_classification/colab/mobile_vit_mpt.ipynb, test/image_classification/colab/mobile_vit_tfl.ipynb, test/image_segmentation/colab/isnet_mpt.ipynb, test/image_segmentation/colab/isnet_tfl.ipynb
Manually tested that the Colabs all run.
BUG=http://b/340367182
=> Update all Colabs in the repo to use ai-edge-torch-nightly.

format.sh
Address [this comment](https://github.com/google-ai-edge/ai-edge-torch/pull/8#discussion_r1605682929)
BUG=cleanup
=> Address review comment from PR#8

ai_edge_torch/generative/test/loader_test.py
Add unit tests to ensure correctness of loader utilities.
BUG=adding test
=> Add test for the loader module.

ai_edge_torch/convert/fx_passes/build_aten_composite_pass.py, ai_edge_torch/convert/fx_passes/test/test_build_aten_composite_pass.py, ai_edge_torch/convert/test/test_convert_composites.py, requirements.txt
=> Enable composite for avg_pool2d in ceil_mode

ai_edge_torch/convert/test/test_convert.py
=> Fix tflite flags test

ai_edge_torch/convert/fx_passes/build_aten_composite_pass.py, ai_edge_torch/convert/fx_passes/test/test_build_aten_composite_pass.py, ai_edge_torch/convert/test/test_convert_composites.py, requirements.txt
=> Wrap GELU in composite so that it is lowered to tfl.gelu

requirements.txt
=> Update tf-nightly dep

ai_edge_torch/generative/examples/stable_diffusion/convert_to_tflite.py, ai_edge_torch/generative/examples/stable_diffusion/decoder.py, ai_edge_torch/generative/examples/stable_diffusion/encoder.py, ai_edge_torch/generative/layers/attention.py, ai_edge_torch/generative/layers/builder.py, ai_edge_torch/generative/layers/model_config.py, ai_edge_torch/generative/layers/unet/__init__.py, ai_edge_torch/generative/layers/unet/blocks_2d.py, ai_edge_torch/generative/layers/unet/builder.py, ai_edge_torch/generative/layers/unet/model_config.py, ai_edge_torch/generative/utilities/autoencoder_loader.py, ai_edge_torch/generative/utilities/loader.py
Refactor decoder of stable diffusion to use layers of generative API.
There are three commits inside the PR.
1.  Add group norm 
2. Add blocks modules and configs used in autoencoder
3. Refactor decoder of stable diffusion, add model loader and update `convert_to_tflite.py` pipeline
=> Refactor decoder of stable diffusion

ai_edge_torch/generative/layers/model_config.py
Add back missed deleted GELU_QUICK type.
=> Add back missed deleted GELU_QUICK type.

ai_edge_torch/generative/utilities/autoencoder_loader.py
Fix activation_config renaming in autoencolder_loader.
=> Fix activation_config renaming in autoencolder_loader

ai_edge_torch/generative/examples/t5/t5_attention.py, ai_edge_torch/generative/layers/attention.py, ai_edge_torch/generative/utilities/t5_loader.py
Add cross attention layer and refactor t5_attention to inherit from cross attention.
Test the t5 conversion and work.
=> Add cross attention layer and refactor t5_attention

ai_edge_torch/generative/examples/stable_diffusion/decoder.py, ai_edge_torch/generative/layers/unet/blocks_2d.py, ai_edge_torch/generative/layers/unet/builder.py, ai_edge_torch/generative/layers/unet/model_config.py
Add 2D blocks used in diffusion model of stable diffusion.
1. FeedForwardBlock2D: used in TransformerBlock2D
1. CrossAttentionBlock2D: used in TransformerBlock2D
1. TransformerBlock2D: used in DownEncoder2DBlock and SkipUpDecoderBlock2D
1. DownEncoder2DBlock: used in encoders of diffusion model
1. SkipUpDecoderBlock2D: used in decoders of diffusion model
=> Add 2D blocks used in diffusion model of stable diffusion.

ai_edge_torch/generative/examples/stable_diffusion/decoder.py, ai_edge_torch/generative/layers/unet/blocks_2d.py
1. Fix UpDecoder config.
2. Remove ModuleList of optional blocks.
nn.Module seems cannot contain empty ModuleList
=> Fix broken decoder conversion of SD.

ai_edge_torch/generative/layers/attention.py, ai_edge_torch/generative/layers/model_config.py, ai_edge_torch/generative/test/test_model_conversion.py
Remove the restriction of batch_size = 1.
BUG=None
=> support batch > 1 and add batch_size to model config.

ai_edge_torch/convert/conversion.py, ai_edge_torch/generative/fx_passes/__init__.py, ai_edge_torch/generative/fx_passes/remove_sdpa_zero_mask_pass.py, ai_edge_torch/generative/fx_passes/test/test_remove_sdpa_zero_mask_pass.py
BUG=https://b.corp.google.com/issues/347110617
=> Add fx pass to remove sdpa composite zero mask input

ai_edge_torch/generative/layers/README.md, ai_edge_torch/generative/layers/unet/README.md
Add README for unet layers.
BUG=None
=> Add README for unet layers.

ai_edge_torch/__init__.py, ai_edge_torch/convert/test/test_to_channel_last_io.py, ai_edge_torch/convert/to_channel_last_io.py
doc https://docs.google.com/document/d/1GZuWmhTg8wgUnzlvgwj7aBA0DFTswJZmNHuYBDT3AFE/edit?tab=t.0
BUG=https://b.corp.google.com/issues/348473434
=> Add channel last IO transformation API

ai_edge_torch/generative/examples/gemma/convert_to_tflite.py, ai_edge_torch/generative/examples/gemma/gemma.py, ai_edge_torch/generative/examples/phi2/convert_to_tflite.py, ai_edge_torch/generative/examples/phi2/phi2.py, ai_edge_torch/generative/examples/stable_diffusion/clip.py, ai_edge_torch/generative/examples/stable_diffusion/convert_to_tflite.py, ai_edge_torch/generative/examples/t5/convert_to_tflite.py, ai_edge_torch/generative/examples/t5/t5.py, ai_edge_torch/generative/examples/test_models/toy_model.py, ai_edge_torch/generative/examples/test_models/toy_model_with_external_kv_cache.py, ai_edge_torch/generative/examples/test_models/toy_model_with_kv_cache.py, ai_edge_torch/generative/examples/tiny_llama/convert_to_tflite.py, ai_edge_torch/generative/examples/tiny_llama/tiny_llama.py, ai_edge_torch/generative/quantize/example.py, ai_edge_torch/generative/test/test_model_conversion.py, ai_edge_torch/generative/test/test_quantize.py
=> Change tokens from i64 to i32

requirements.txt
=> Pin ai-edge-quantizer nightly version

ai_edge_torch/generative/examples/gemma/convert_to_tflite.py, ai_edge_torch/generative/examples/gemma/gemma.py, ai_edge_torch/generative/examples/phi2/convert_to_tflite.py, ai_edge_torch/generative/examples/phi2/phi2.py, ai_edge_torch/generative/examples/stable_diffusion/clip.py, ai_edge_torch/generative/examples/stable_diffusion/convert_to_tflite.py, ai_edge_torch/generative/examples/t5/convert_to_tflite.py, ai_edge_torch/generative/examples/t5/t5.py, ai_edge_torch/generative/examples/test_models/toy_model.py, ai_edge_torch/generative/examples/test_models/toy_model_with_external_kv_cache.py, ai_edge_torch/generative/examples/test_models/toy_model_with_kv_cache.py, ai_edge_torch/generative/examples/tiny_llama/convert_to_tflite.py, ai_edge_torch/generative/examples/tiny_llama/tiny_llama.py, ai_edge_torch/generative/quantize/example.py, ai_edge_torch/generative/test/test_model_conversion.py, ai_edge_torch/generative/test/test_quantize.py
This reverts commit 2f133e427b3ec06bba6c5b8c9a05544a77ab0987.
BUG=N/A
=> Revert "Change tokens from i64 to i32 (#68)"

setup.py
Fix regression caused by https://github.com/google-ai-edge/ai-edge-torch/pull/76 in model coverage tests
BUG=https://b.corp.google.com/issues/348401909
=> Fix torch requirement

ai_edge_torch/generative/examples/t5/t5_attention.py
Fixes T5 model inference
BUG=https://buganizer.corp.google.com/issues/352073514
=> Call CrossAttention __init__ with batch dim

ai_edge_torch/generative/examples/stable_diffusion/README.md, ai_edge_torch/generative/examples/stable_diffusion/clip.py, ai_edge_torch/generative/examples/stable_diffusion/convert_to_tflite.py, ai_edge_torch/generative/examples/stable_diffusion/decoder.py, ai_edge_torch/generative/examples/stable_diffusion/diffusion.py, ai_edge_torch/generative/examples/stable_diffusion/pipeline.py, ai_edge_torch/generative/layers/model_config.py, ai_edge_torch/generative/layers/unet/blocks_2d.py, ai_edge_torch/generative/layers/unet/model_config.py, ai_edge_torch/generative/utilities/loader.py, ai_edge_torch/generative/utilities/stable_diffusion_loader.py
- Add tensor names mapping from original SD 1.5 huggingface repo https://huggingface.co/runwayml/stable-diffusion-v1-5
- Fix some miscellaneous typos
BUG=b/350994822
=> Add safetensors SD 1.5 tensor names mapping

ai_edge_torch/generative/fx_passes/remove_sdpa_zero_mask_pass.py
=> Fix SDPA FX pass for mask input

ai_edge_torch/convert/fx_passes/build_aten_composite_pass.py, ai_edge_torch/convert/fx_passes/test/test_build_aten_composite_pass.py, ai_edge_torch/convert/test/test_convert_composites.py
=> Wrap embedding tables with HLFB

requirements.txt
=> Update ai-edge-quantizer-nightly version

ai_edge_torch/convert/conversion_utils.py, ai_edge_torch/convert/test/test_convert.py
Add support for composite keyword arguments.
BUG=b/353293690
=> Add support for composite kwargs

ai_edge_torch/generative/layers/unet/blocks_2d.py
Fix missing group norm in converted TF Lite models.
Verified the e2e pipeline with newly converted models.
BUG=b/355109848
=> Fix missing group norm in converted TF Lite models.

docs/pytorch_converter/README.md
BUG=https://b.corp.google.com/issues/354982556
=> Add to_channel_last_io doc to converter readme

ai_edge_torch/README.md, docs/pytorch_converter/README.md
BUG=https://b.corp.google.com/issues/354982556
=> Add link to to_channel_last_io test as example

README.md
=> Fix torch badge in readme

ai_edge_torch/convert/fx_passes/build_aten_composite_pass.py
=> Disable embedding composite for non-2D embedding tables

ai_edge_torch/generative/examples/stable_diffusion/convert_to_tflite.py, ai_edge_torch/generative/examples/stable_diffusion/pipeline.py, ai_edge_torch/generative/quantize/README.md
BUG=b/355505876
Verified with pipeline.py
=> Add quantization for StableDiffusion

ai_edge_torch/version.py, setup.py
Allow `print(ai_edge_torch.__version__)`
BUG=https://buganizer.corp.google.com/issues/357076369
=> Add version.py and ai_edge_torch.__version__

ai_edge_torch/_convert/fx_passes/optimize_layout_transposes_pass/layout_rewrite.py
=> Fix batch norm when weight/bias is None

docs/pytorch_converter/README.md
Small PR - Commit 992ad4d7b001f2aceab9f2c95d224a4503b9816f moved the `test_to_channel_last_io.py` file. This PR adjusts sources to changes.
=> Update `test_to_channel_last_io.py` reference
